### ISSUE TITLE
Repo clarification

### ISSUE THREAD

**Issue by lurch** [RPi-Distro/rc_gui#1]
I'm guessing this repo https://github.com/RPi-Distro/rc_gui is a kind of "manually updated downstream clone" of https://github.com/raspberrypi/rc_gui ?
Might be nice if where https://github.com/RPi-Distro/rc_gui currently says _No description or website provided._ you could clarify this situation, and explain that issues should be filed against the 'upstream' https://github.com/raspberrypi/rc_gui repo?

**Comment by XECDesign** [comment]
This repo is for packaging of rc_gui. At this point, the packaging files could be added back to raspberrypi/rc_gui and this repo deleted, but we have a workflow sorted which allows packages to be updated relatively quickly, so we're sticking with it until there's a reason to change it. It doesn't matter where issues are reported, they'll get forwarded to the right person.
